# Generated by Django 4.0.3 on 2023-01-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equip_app', '0002_organization_equipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='organization',
            new_name='organization_id',
        ),
    ]
